### ISSUE TITLE
我遇到一个谷歌解决不了的问题

### ISSUE THREAD

**Issue by noiver** [ze00/sad#1]

**Comment by noiver** [comment]
ERROR: /home/zerozaki/work/mk7/packages/apps/Dialer/tests/src/com/andro                                                                                                id/dialer/database/DialerDatabaseHelperTest.java:150: The constructor S                                                                                                martDialNameMatcher(String, SmartDialMap) is undefined
ninja: build stopped: subcommand failed.
make: *** [ninja_wrapper] 错误 1

**Comment by ze00** [comment]
@noiver 也只不过是个tests...
直接注释/删掉就行了
